### ISSUE TITLE
I clone by Android Studio，clone is successful but build is faild

### ISSUE THREAD

**Issue by Aaron1995** [bin456789/Unblock163MusicClient-Xposed#1]
我发现作者是国人。。直接用中文好了。。在Android Studio直接clone下来后出现了这个错误
Error:(4, 0) D:\Users\Aaron\AndroidStudioProjects\WorkPlace1\Unblock163MusicClient-Xposed\private\signing.properties (系统找不到指定的路径。)
<a href="openFile:D:\Users\Aaron\AndroidStudioProjects\WorkPlace1\Unblock163MusicClient-Xposed\app\build.gradle">Open File</a>
请问一下private这个文件夹是没有么？

**Comment by bin456789** [comment]
文件夹里放的是签名配置，不会放到 github 上的
解决办法是打开 app\build.gradle 删除关于 signing 的内容

**Comment by Aaron1995** [comment]
谢谢！之前一直在忙家里的事很少上，没有及时回复，请谅解！
之后我再clean后可以build gradle但是却一直无法安装到模拟器上
java.lang.SecurityException: No permission to write APN settings: Neither user *** nor current process has android.permission.WRITE_APN_SETTINGS.
这个我在网上查找了一下似乎是说apk签名的问题？
就算我签名了release也不能够运行 
请问一下我应该怎么将其安装上模拟器上？

**Comment by bin456789** [comment]
这个我也不清楚，我都是用真机测试的

**Comment by Aaron1995** [comment]
好的  谢谢
