### ISSUE TITLE
网易云音乐3.5.0版MOD失效

### ISSUE THREAD

**Issue by mikelei8291** [bin456789/Unblock163MusicClient-Xposed#10]

**Comment by djun** [comment]
失效，并且回退旧版本也不能用了，忧伤

**Comment by mxalbert1996** [comment]
我这里没问题

**Comment by bin456789** [comment]
网易的服务器上删除了下架的歌曲，所以失效了。。

**Comment by sino1641** [comment]
@bin456789 
[github.com/loadfield/go-music](url) ←实测能用
据说也是原来的API-_-||

**Comment by bin456789** [comment]
@sino1641 
试了下能用
也是原来的API
只不过网易将下架歌曲搬到图片服务器上了。。让人捉摸不定。。

**Comment by bin456789** [comment]
另外，装了插件时，播放下架歌曲前会先用http head测试歌曲是否存在
由于插件代码质量问题，同样的报文发到这组图片服务器就识别不了
所以新的代码暂时停用了http head测试
所以要更新apk

**Comment by aviraxp** [comment]
看来是又能用了？顺便加上新版支持呗~

**Comment by sino1641** [comment]
@bin456789 感谢回复及更新
~~作为一个PM 问下能否直接根据下载速度判断歌曲是否存在？~~

**Comment by bin456789** [comment]
@sino1641 
目测可以，研究中
