### ISSUE TITLE
Handler.isDomainExpired 问题请教

### ISSUE THREAD

**Issue by tiann** [bin456789/Unblock163MusicClient-Xposed#126]
这个意思是，2018年10月，这个插件就无法工作了吗？

**Comment by 244276041** [comment]
你从哪里看到2018年10月，这个插件就无法工作了？

**Comment by tiann** [comment]
代码：https://github.com/bin456789/Unblock163MusicClient-Xposed/blob/master/app/src/main/java/bin/xposed/Unblock163MusicClient/Main.java#L31

**Comment by bin456789** [comment]
是，那时候域名过期，看情况要不要换新域名，毕竟新注册便宜
顺便还能减少一波使用人数

**Comment by tiann** [comment]
好的，谢谢
