### ISSUE TITLE
同张专辑其他歌曲可以 只有一首资源不存在

### ISSUE THREAD

**Issue by fanghuan27** [bin456789/Unblock163MusicClient-Xposed#141]
分享BLACKPINK的单曲《뚜두뚜두 (DDU-DU DDU-DU)》: http://music.163.com/song/573577071/?userid=11168074 (来自@网易云音乐)

能解决吗

**Comment by bin456789** [comment]
能解决，需要点时间

**Comment by fanghuan27** [comment]
谢谢作者！

**Comment by bin456789** [comment]
已解决
