### ISSUE TITLE
求电脑版的音量增强

### ISSUE THREAD

**Issue by mlgexyz** [bin456789/Unblock163MusicClient-Xposed#143]
希望作者大大能够写一个可供 windows 网易云 使用的音量增强，如果可以的话。
如果作者您没时间或者力不能及，能否烦请您将软件工作原理告知于我（看不懂java是硬伤），我来试着写一下？

**Comment by steven7851** [comment]
电脑版类似的很多了 自己搜寻一下
https://github.com/nondanee/UnblockNeteaseMusic
