### ISSUE TITLE
下载进度条走完了，然后弹出个下载失败。。。

### ISSUE THREAD

**Issue by tmaccx** [bin456789/Unblock163MusicClient-Xposed#15]
0.0.7+最新版网易云+flyme5

**Comment by bin456789** [comment]
是什么歌曲和音质？

**Comment by 504109543** [comment]
我的是0.0.9,网易云3.6.0.143673 ,flyme5
测试下载够钟-周柏豪,极高和较高、标准音质失败

**Comment by bin456789** [comment]
http://pan.baidu.com/s/1pLCjdmb
下载这个版本试试看

**Comment by 504109543** [comment]
嗯，安装以后。在下载管理里面看是下载失败的，而且用文件管理器看下载目录也没有文件。请问会有打log吗？或许我可以提供一下log

**Comment by bin456789** [comment]
@504109543 本地没有log的
但我发给你的apk中，在这里上传了path到我的服务器上，所以也算是打了log
https://github.com/bin456789/Unblock163MusicClient-Xposed/blob/master/app/src/main/java/bin/xposed/Unblock163MusicClient/Main.java#L114

我发现有些歌曲下载路径在这里
/Android/data/com.netease.cloudmusic/files/Documents/Cache/Download/
这可能就是下载失败的原因

再试试这个版本吧
http://pan.baidu.com/s/1c2oOWZA

**Comment by 504109543** [comment]
@bin456789 不好意思最近有点忙,我说一下我使用时候的情况吧(在登录情况下正常听歌使用一段时间)
1、如果是云音乐的默认下载路径(内置sd)的话，我试过是可以下载成功的,当然无损音质除外
2、至于你所说下载路径，我找过里面没有文件
3、当我将下载路径修改为外置sd时就会出现下载失败的情况
有时间的话，我想帮忙debug下，希望这个插件越做越好:-)

**Comment by yoyodadada** [comment]
这种情况我也遇到过，不过是TCL定制版9.0.0的，安卓5.0.2，华为EMUI3.1，换做现在最新的4.0.0+0.0.16插件没有问题了

**Comment by yoyodadada** [comment]
想问作者，明明下载进度条都走完了，最后提示失败的原因会是什么呢？真的是因为我的网易云音乐是定制版的么？

**Comment by bin456789** [comment]
@yoyodadada 这个版本号是9.0.0，由于9大于4，插件当它4.x来处理，所以会出现问题，你可以试试0.0.15。

**Comment by yoyodadada** [comment]
@bin456789 0.0.15在Releases没有下载，哪里能下载到？

**Comment by yoyodadada** [comment]
@bin456789 在网上找到的0.0.15版本：http://soft.shouji.com.cn/down/32523.html，配上TCL定制版，经过测试，可以下载常规无法下载的歌曲，而且不会出现下载失败的提示了，感谢作者！

**Comment by yoyodadada** [comment]
还是请大神给一个正版的0.0.15，我担心我下载的有问题

**Comment by bin456789** [comment]
@yoyodadada 呃，要是github上的16能覆盖安装你找的15，那个15就没问题

**Comment by yoyodadada** [comment]
@bin456789 谢谢，能覆盖安装。

**Comment by huangjua** [comment]
作者你好，0.016对最新网易云好像失效了

**Comment by bin456789** [comment]
@huangjua 我测试了下4.0.1没发现失效

**Comment by bin456789** [comment]
@tmaccx 
@504109543
关于下载失败这个问题
我有一台远古的红米，系统版本是4.1，在这台手机下载下架歌曲到外置sd卡是正常的
所以我猜测，下载失败是因为某些安卓版本（4.4+）限制写入外置sd卡引起的。
不过我没其他设备测试，所以这个问题一直拖着
我先把issue关闭了，假如是普通歌曲能下载到外置sd卡，但下架歌曲不能的话，那就重开issue吧

**Comment by huangjua** [comment]
@bin456789 ...好，我再测试看看

**Comment by huangjua** [comment]
@bin456789 ...好，我再测试看看。
