### ISSUE TITLE
等更新～催一波

### ISSUE THREAD

**Issue by Maybe0019** [bin456789/Unblock163MusicClient-Xposed#166]
抓一波log
bin.xposed.Unblock163MusicClient.a$c.a(Unknown Source:151)
10-31 00:43:47.130 E/Xposed (26204): at bin.xposed.Unblock163MusicClient.a.a(Unknown Source:21)
10-31 00:43:47.130 E/Xposed (26204): at bin.xposed.Unblock163MusicClient.Main$1.afterHookedMethod(Unknown Source:21)
10-31 00:43:47.130 E/Xposed (26204): at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:375)
10-31 00:43:47.130 E/Xposed (26204): at android.app.Application.attach()
10-31 00:43:47.130 E/Xposed (26204): at android.app.Instrumentation.newApplication(Instrumentation.java:1103)
10-31 00:43:47.130 E/Xposed (26204): at android.app.Instrumentation.newApplication(Instrumentation.java:1087)
10-31 00:43:47.130 E/Xposed (26204): at android.app.LoadedApk.makeApplication(LoadedApk.java:972)
10-31 00:43:47.130 E/Xposed (26204): at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5851)
10-31 00:43:47.130 E/Xposed (26204): at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
10-31 00:43:47.130 E/Xposed (26204): at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:361)
10-31 00:43:47.130 E/Xposed (26204): at android.app.ActivityThread.handleBindApplication()
10-31 00:43:47.130 E/Xposed (26204): at android.app.ActivityThread.-wrap1(Unknown Source:0)
10-31 00:43:47.130 E/Xposed (26204): at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1690)
10-31 00:43:47.130 E/Xposed (26204): at android.os.Handler.dispatchMessage(Handler.java:105)
10-31 00:43:47.130 E/Xposed (26204): at android.os.Looper.loop(Looper.java:173)
10-31 00:43:47.130 E/Xposed (26204): at android.app.ActivityThread.main(ActivityThread.java:6698)
10-31 00:43:47.130 E/Xposed (26204): at java.lang.reflect.Method.invoke(Native Method)
10-31 00:43:47.130 E/Xposed (26204): at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
10-31 00:43:47.130 E/Xposed (26204): at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:782)
10-31 00:43:47.130 E/Xposed (26204): at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:108)
10-31 00:43:49.857 E/Xposed (26274): java.util.NoSuchElementException: No value present
10-31 00:43:49.857 E/Xposed (26274): at a.a.a.e.b(Unknown Source:8)
10-31 00:43:49.857 E/Xposed (26274): at bin.xposed.Unblock163MusicClient.a$c.a(Unknown Source:151)
10-31 00:43:49.857 E/Xposed (26274): at bin.xposed.Unblock163MusicClient.a.a(Unknown Source:21)
10-31 00:43:49.857 E/Xposed (26274): at bin.xposed.Unblock163MusicClient.Main$1.afterHookedMethod(Unknown Source:21)
10-31 00:43:49.857 E/Xposed (26274): at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:375)
10-31 00:43:49.857 E/Xposed (26274): at android.app.Application.attach()
部分log（不怎么会抓），应该就是没更新，不支持新版本～作者可能比较忙吧

**Comment by rambosir** [comment]
是27版本么，无效了是吗

**Comment by CHN-beta** [comment]
对，27版本无效了

**Comment by nishenge** [comment]
大佬 27版失效了  我能催更一下么

**Comment by CJN1986** [comment]
其实还能用。请退回旧版云村
