### ISSUE TITLE
与温州银行3.5.9冲突

### ISSUE THREAD

**Issue by rxzcums** [bin456789/Unblock163MusicClient-Xposed#175]
miui10 9.1.24 (安卓8.1)
edxposed 0.2.9.8
启用模块后，温州银行app无法开启，禁用后正常。

感谢提供大音量。

**Comment by rxzcums** [comment]
对了，温州银行要加edxposed黑名单。

**Comment by rxzcums** [comment]
经测试，0.30已修复此问题，感谢作者！

**Comment by bin456789** [comment]
不是我的锅，应该是温州银行有xp检测

**Comment by rxzcums** [comment]
> 不是我的锅，应该是温州银行有xp检测

我明白了，说得对，不一定是放大器的锅。
很奇怪的bug，情况是这样的：
1.温州银行和中国移动，两个app均检测xp（检测到就拒绝运行或卡启动页）。
2.我将他们都加入edxp黑名单模式下的的黑名单中，两者均能运行（黑名单功能有效，因为防xp检测成功）
3.装上音量放大器后，两者都不能运行（黑名单功能失效？）
疑似音量放大器与edxp的黑名单功能冲突，是要向edxp那边反映bug吗？请指点迷津。

**Comment by rxzcums** [comment]
edxposed 0.2.9.9.b2已解决此问题，打扰了。
