### ISSUE TITLE
考不考虑加一个“禁止软件更新”？

### ISSUE THREAD

**Issue by Maybe0019** [bin456789/Unblock163MusicClient-Xposed#193]
毕竟这个模块更新不一定及时，不更新软件的话每次启动都提示更新，更新了软件插件又失效…
还有，能不能给插件做个热更新？或者检测最新版本，再给个github地址让用户自己下载也行啊

**Comment by bin456789** [comment]
不考虑，你都知道这里了

**Comment by yaohunzhanyue** [comment]
你都用xp了，为什么不再用个对话框取消模块呢
