### ISSUE TITLE
Tested not working for version 3.1.4

### ISSUE THREAD

**Issue by lianxiangru** [bin456789/Unblock163MusicClient-Xposed#2]
Even though the readme claims that v3.1.4 is compatible with the module, I did not manage to have the blocked items available in it.

I can get into the playing UI but it seems that the streaming has never started.

--------
Update: I can confirm that for some pieces of music the unblocking is working. For most music (especially Japanese), it does not work.

**Comment by bin456789** [comment]
现在很多歌曲已经从cdn上移除了，这个无法解决。。
