### ISSUE TITLE
所有歌都是资源不存在是失效了吗？

### ISSUE THREAD

**Issue by GaHoKwan** [bin456789/Unblock163MusicClient-Xposed#220]
网易云，6.1.0
插件，0.0.34
所有变灰歌都是资源不存在

**Comment by L95210** [comment]
是啊 不知道作者还会不会更新

**Comment by L95210** [comment]
提示：模块已经过期了，请更新。

**Comment by JasonKhew96** [comment]
![image](https://user-images.githubusercontent.com/29531167/66265666-d1692c00-e84c-11e9-810b-d6372ea74468.png)
急的话自己改

**Comment by maple3142** [comment]
有需要修改過的 apk 的話可以到這邊下載: https://circleci.com/gh/maple3142/Unblock163MusicClient-Xposed/5#artifacts/containers/0

**Comment by xmsjshou** [comment]
@maple3142 感谢！是dubug目录下的app吗

**Comment by maple3142** [comment]
@xmsjshou 對

**Comment by a2212997715** [comment]
好心人给个链接啊

**Comment by ZaneCode6574** [comment]
单改日期没有用的

**Comment by a2212997715** [comment]
还是不能用啊6.4.1

**Comment by qq171161636** [comment]
> 有需要修改过的apk的话可以到这边下载：[https](https://circleci.com/gh/maple3142/Unblock163MusicClient-Xposed/5#artifacts/containers/0) ://circleci.com/gh/maple3142/Unblock163MusicClient-Xposed/5#artifacts/containers/0[](https://circleci.com/gh/maple3142/Unblock163MusicClient-Xposed/5#artifacts/containers/0)

还是不能用啊！！！

**Comment by SnailInLeaves** [comment]
> 有需要修改過的 apk 的話可以到這邊下載: https://circleci.com/gh/maple3142/Unblock163MusicClient-Xposed/5#artifacts/containers/0

這裡面哪有下載？

**Comment by maple3142** [comment]
@NotFoundNEKKO 裡面有個 Artifacts 就是了

**Comment by echoIIImk2** [comment]
> @NotFoundNEKKO 裡面有個 Artifacts 就是了

点了没反应啊，请问有其他下载链接吗
