### ISSUE TITLE
是不是哪家运营商不给解析了

### ISSUE THREAD

**Issue by aviraxp** [bin456789/Unblock163MusicClient-Xposed#25]
10-02 07:13:00.819 W/System.err(5465): java.net.UnknownHostException: Unable to resolve host "music.xposed.tk": No address associated with hostname

**Comment by aviraxp** [comment]
现在换服务器了？

**Comment by bin456789** [comment]
现在我这边也解析不了，所有tk、ml域名都不行，只能换个正规点的域名

**Comment by aviraxp** [comment]
我翻墙了还可以，dns换成114.114.114.114也行

**Comment by aviraxp** [comment]
能不能加个尝试机制或者手动切换，因为有人新的域名有问题，老的域名没事

**Comment by bin456789** [comment]
用回旧版就行。。而且top域名应该不会有事，毕竟可以备案
