### ISSUE TITLE
服务器发生错误

### ISSUE THREAD

**Issue by davidtaysnow88** [bin456789/Unblock163MusicClient-Xposed#26]
如题。
刚刚下载和在线听都不能使用了。
是不是模块要更新，
还是我的问题..

**Comment by bin456789** [comment]
用0.0.12试试，我这部正常
如果还不行，提供下歌名让我瞧瞧。。

**Comment by davidtaysnow88** [comment]
基本要付费歌曲和中国大陆限制的所有音乐都不能播放。
刚刚我播放的 Rachel Platten - Fight Song 和 One Republic 的最新数字专辑都不能播放，也不能下载。试了播林俊杰的歌也不行。。
添加至下载列表过后要下载时直接toast显示 “服务器发生错误“。

**Comment by aviraxp** [comment]
[app-release.zip](https://github.com/bin456789/Unblock163MusicClient-Xposed/files/518187/app-release.zip)

试试这个。

**Comment by davidtaysnow88** [comment]
还是一样

**Comment by aviraxp** [comment]
翻墙或者换dns为114.114.114.114试试

**Comment by davidtaysnow88** [comment]
都不行。
DNS 1 与 2 都放一样的IP下去对吧？

**Comment by aviraxp** [comment]
会抓logcat吗？抓一个看看

**Comment by davidtaysnow88** [comment]
没抓过，但现在电脑不在身边，用不到adb抓。

**Comment by aviraxp** [comment]
http://www.coolapk.com/apk/com.pluscubed.matlog

**Comment by davidtaysnow88** [comment]
10-09 20:11:31.522 D/NeteaseMusicConst(21441): ignoreAudioFocusChangeConfig:com.kugou.android,com.yibasan.lizhifm|6040,2147483647
10-09 20:11:31.535 D/NeteaseMusicConst(21441): scanAutoFilterPaths:/storage/emulated/0/tencent/,/storage/emulated/0/moji/,/storage/emulated/0/Tencent/,/storage/emulated/0/Yixin/
10-09 20:11:31.536 D/NeteaseMusicConst(21441): scanWhitePaths:/storage/emulated/0/qqmusic/offline/
10-09 20:11:34.563 D/NeteaseMusicConst(21517): ignoreAudioFocusChangeConfig:com.kugou.android,com.yibasan.lizhifm|6040,2147483647
10-09 20:11:34.571 D/NeteaseMusicConst(21517): scanAutoFilterPaths:/storage/emulated/0/tencent/,/storage/emulated/0/moji/,/storage/emulated/0/Tencent/,/storage/emulated/0/Yixin/
10-09 20:11:34.573 D/NeteaseMusicConst(21517): scanWhitePaths:/storage/emulated/0/qqmusic/offline/
10-09 20:11:36.004 D/NeteaseMusicConst(21441): scanAutoFilterPaths:/storage/emulated/0/tencent/,/storage/emulated/0/HJApp/,/storage/emulated/0/leci/,/storage/emulated/0/baicizhan/,/storage/emulated/0/Tencent/,/storage/emulated/0/Recorder/,/storage/emulated/0/Yixin/,/storage/emulated/0/RM/,/storage/emulated/0/moji/,/storage/emulated/0/Android/,/storage/emulated/0/towords/
10-09 20:11:36.013 D/NeteaseMusicConst(21441): scanWhitePaths:/storage/emulated/0/tencent/QQfile_recv/,/storage/emulated/0/qqmusic/offline/
10-09 20:11:36.014 D/NeteaseMusicConst(21441): ignoreAudioFocusChangeConfig:com.kugou.android,com.yibasan.lizhifm,com.netease.newsreader.activity|6040,2147483647,2147483647

**Comment by davidtaysnow88** [comment]
是这个？

**Comment by aviraxp** [comment]
给个全的

**Comment by davidtaysnow88** [comment]
10-09 20:11:31.522 D/NeteaseMusicConst(21441): ignoreAudioFocusChangeConfig:com.kugou.android,com.yibasan.lizhifm|6040,2147483647
10-09 20:11:31.535 D/NeteaseMusicConst(21441): scanAutoFilterPaths:/storage/emulated/0/tencent/,/storage/emulated/0/moji/,/storage/emulated/0/Tencent/,/storage/emulated/0/Yixin/
10-09 20:11:31.536 D/NeteaseMusicConst(21441): scanWhitePaths:/storage/emulated/0/qqmusic/offline/
10-09 20:11:34.563 D/NeteaseMusicConst(21517): ignoreAudioFocusChangeConfig:com.kugou.android,com.yibasan.lizhifm|6040,2147483647
10-09 20:11:34.571 D/NeteaseMusicConst(21517): scanAutoFilterPaths:/storage/emulated/0/tencent/,/storage/emulated/0/moji/,/storage/emulated/0/Tencent/,/storage/emulated/0/Yixin/
10-09 20:11:34.573 D/NeteaseMusicConst(21517): scanWhitePaths:/storage/emulated/0/qqmusic/offline/
10-09 20:11:36.004 D/NeteaseMusicConst(21441): scanAutoFilterPaths:/storage/emulated/0/tencent/,/storage/emulated/0/HJApp/,/storage/emulated/0/leci/,/storage/emulated/0/baicizhan/,/storage/emulated/0/Tencent/,/storage/emulated/0/Recorder/,/storage/emulated/0/Yixin/,/storage/emulated/0/RM/,/storage/emulated/0/moji/,/storage/emulated/0/Android/,/storage/emulated/0/towords/
10-09 20:11:36.013 D/NeteaseMusicConst(21441): scanWhitePaths:/storage/emulated/0/tencent/QQfile_recv/,/storage/emulated/0/qqmusic/offline/
10-09 20:11:36.014 D/NeteaseMusicConst(21441): ignoreAudioFocusChangeConfig:com.kugou.android,com.yibasan.lizhifm,com.netease.newsreader.activity|6040,2147483647,2147483647

**Comment by davidtaysnow88** [comment]
等等弄错了

**Comment by davidtaysnow88** [comment]
http://pan.baidu.com/share/link?shareid=3592910358&uk=1077769528

**Comment by aviraxp** [comment]
```
10-09 20:11:33.578 E/Xposed  (21517): java.lang.NoSuchMethodError: com.netease.cloudmusic.i.a$1#determineRoute(com.netease.mam.org.apache.http.HttpHost,com.netease.mam.org.apache.http.HttpRequest,com.netease.mam.org.apache.http.protocol.HttpContext)#exact
10-09 20:11:33.578 E/Xposed  (21517): 	at de.robv.android.xposed.XposedHelpers.findMethodExact(XposedHelpers.java:337)
10-09 20:11:33.578 E/Xposed  (21517): 	at de.robv.android.xposed.XposedHelpers.findAndHookMethod(XposedHelpers.java:178)
10-09 20:11:33.578 E/Xposed  (21517): 	at de.robv.android.xposed.XposedHelpers.findAndHookMethod(XposedHelpers.java:253)
10-09 20:11:33.578 E/Xposed  (21517): 	at bin.xposed.Unblock163MusicClient.j.afterHookedMethod(SourceFile:170)
10-09 20:11:33.578 E/Xposed  (21517): 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:348)
10-09 20:11:33.578 E/Xposed  (21517): 	at android.app.Application.attach(<Xposed>)
10-09 20:11:33.578 E/Xposed  (21517): 	at android.app.Instrumentation.newApplication(Instrumentation.java:998)
10-09 20:11:33.578 E/Xposed  (21517): 	at android.app.Instrumentation.newApplication(Instrumentation.java:982)
10-09 20:11:33.578 E/Xposed  (21517): 	at android.app.LoadedApk.makeApplication(LoadedApk.java:574)
10-09 20:11:33.578 E/Xposed  (21517): 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4724)
10-09 20:11:33.578 E/Xposed  (21517): 	at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
10-09 20:11:33.578 E/Xposed  (21517): 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:334)
10-09 20:11:33.578 E/Xposed  (21517): 	at android.app.ActivityThread.handleBindApplication(<Xposed>)
10-09 20:11:33.578 E/Xposed  (21517): 	at android.app.ActivityThread.-wrap1(ActivityThread.java)
10-09 20:11:33.578 E/Xposed  (21517): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1424)
10-09 20:11:33.578 E/Xposed  (21517): 	at android.os.Handler.dispatchMessage(Handler.java:102)
10-09 20:11:33.578 E/Xposed  (21517): 	at android.os.Looper.loop(Looper.java:148)
10-09 20:11:33.578 E/Xposed  (21517): 	at android.app.ActivityThread.main(ActivityThread.java:5461)
10-09 20:11:33.578 E/Xposed  (21517): 	at java.lang.reflect.Method.invoke(Native Method)
10-09 20:11:33.578 E/Xposed  (21517): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
10-09 20:11:33.578 E/Xposed  (21517): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
10-09 20:11:33.578 E/Xposed  (21517): 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:102)
```
要定位的话问题在这里https://github.com/bin456789/Unblock163MusicClient-Xposed/blob/a93a650484718c9ad8c57c7364bbafda1dffabda/app/src/main/java/bin/xposed/Unblock163MusicClient/Main.java#L170

**Comment by aviraxp** [comment]
还有这个
```
10-09 20:11:41.163 W/System.err(21441): org.json.JSONException: No value for md5
10-09 20:11:41.163 W/System.err(21441): 	at org.json.JSONObject.get(JSONObject.java:389)
10-09 20:11:41.163 W/System.err(21441): 	at org.json.JSONObject.getString(JSONObject.java:550)
10-09 20:11:41.163 W/System.err(21441): 	at com.netease.cloudmusic.c.a.c.m(ProGuard:1005)
10-09 20:11:41.163 W/System.err(21441): 	at com.netease.cloudmusic.c.a.c.a(ProGuard:10854)
10-09 20:11:41.163 W/System.err(21441): 	at com.netease.cloudmusic.c.a.c.a(ProGuard:10874)
10-09 20:11:41.163 W/System.err(21441): 	at java.lang.reflect.Method.invoke(Native Method)
10-09 20:11:41.163 W/System.err(21441): 	at com.netease.cloudmusic.utils.b.invoke(ProGuard:51)
10-09 20:11:41.163 W/System.err(21441): 	at java.lang.reflect.Proxy.invoke(Proxy.java:393)
10-09 20:11:41.163 W/System.err(21441): 	at $Proxy0.a(Unknown Source)
10-09 20:11:41.163 W/System.err(21441): 	at com.netease.cloudmusic.fragment.bc.a(ProGuard:538)
10-09 20:11:41.163 W/System.err(21441): 	at com.netease.cloudmusic.fragment.bc.b(ProGuard:525)
10-09 20:11:41.163 W/System.err(21441): 	at com.netease.cloudmusic.d.ad.doInBackground(ProGuard:159)
10-09 20:11:41.163 W/System.err(21441): 	at android.os.AsyncTask$2.call(AsyncTask.java:295)
10-09 20:11:41.163 W/System.err(21441): 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
10-09 20:11:41.163 W/System.err(21441): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
10-09 20:11:41.163 W/System.err(21441): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
10-09 20:11:41.163 W/System.err(21441): 	at java.lang.Thread.run(Thread.java:818)
10-09 20:11:41.163 W/System.err(21441): com.netease.cloudmusic.h.a: 
10-09 20:11:41.164 W/System.err(21441): 	at com.netease.cloudmusic.c.a.c.a(ProGuard:10864)
10-09 20:11:41.164 W/System.err(21441): 	at com.netease.cloudmusic.c.a.c.a(ProGuard:10874)
10-09 20:11:41.164 W/System.err(21441): 	at java.lang.reflect.Method.invoke(Native Method)
10-09 20:11:41.164 W/System.err(21441): 	at com.netease.cloudmusic.utils.b.invoke(ProGuard:51)
10-09 20:11:41.164 W/System.err(21441): 	at java.lang.reflect.Proxy.invoke(Proxy.java:393)
10-09 20:11:41.164 W/System.err(21441): 	at $Proxy0.a(Unknown Source)
10-09 20:11:41.164 W/System.err(21441): 	at com.netease.cloudmusic.fragment.bc.a(ProGuard:538)
10-09 20:11:41.164 W/System.err(21441): 	at com.netease.cloudmusic.fragment.bc.b(ProGuard:525)
10-09 20:11:41.164 W/System.err(21441): 	at com.netease.cloudmusic.d.ad.doInBackground(ProGuard:159)
10-09 20:11:41.164 W/System.err(21441): 	at android.os.AsyncTask$2.call(AsyncTask.java:295)
10-09 20:11:41.164 W/System.err(21441): 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
10-09 20:11:41.164 W/System.err(21441): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
10-09 20:11:41.164 W/System.err(21441): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
10-09 20:11:41.164 W/System.err(21441): 	at java.lang.Thread.run(Thread.java:818)
```

**Comment by davidtaysnow88** [comment]
应该是没更新过，我现在的网易云是3.7.2.150253。

**Comment by bin456789** [comment]
这个3.7.2跟我之前用的3.7.2版本不同。。不过现在问题找到了。。
插件更新之前，你可以先用着3.7.3

**Comment by davidtaysnow88** [comment]
好的。。

**Comment by davidtaysnow88** [comment]
酷安网易刚更新3.7.3

**Comment by davidtaysnow88** [comment]
然后可以用了...
