### ISSUE TITLE
可以过掉校验MD5的代码吗

### ISSUE THREAD

**Issue by qq316107934** [bin456789/Unblock163MusicClient-Xposed#3]
你好，
在结合 https://github.com/Chion82/163-music-unlock 来用，但是安卓的客户端会校验付费歌曲下载的MD5，导致付费歌曲没法下载(网络异常)，能不能把这段校验代码跳过去呢？
谢谢。

**Comment by qq316107934** [comment]
好像是我的版本不匹配的原因，我用的是3.3.1的版本，如果是的话就关闭问题吧...

**Comment by bin456789** [comment]
是可以去掉md5校验，不过相关代码我没放到这里。。。
如果你想要，我也可以把这部分代码发给你

**Comment by qq316107934** [comment]
Email: qq316107934#163.com 能否发给我一份呢，谢谢。

**Comment by qq316107934** [comment]
收到了，谢谢！

**Comment by YiuChoi** [comment]
能不能也发我一份啊me@caiyao.name，非常感谢！
