### ISSUE TITLE
新版又来了NoSuchField

### ISSUE THREAD

**Issue by aviraxp** [bin456789/Unblock163MusicClient-Xposed#30]
```
11-06 23:14:35.602 E/Xposed  ( 8078): java.lang.NoSuchFieldError: Field of type com.netease.cloudmusic.meta.MusicInfo in class com.netease.cloudmusic.activity.TrackDetailActivity
11-06 23:14:35.602 E/Xposed  ( 8078):      at de.robv.android.xposed.XposedHelpers.findFirstFieldByExactType(XposedHelpers.java:166)
11-06 23:14:35.602 E/Xposed  ( 8078):      at bin.xposed.Unblock163MusicClient.a$h.a(Unknown Source)
11-06 23:14:35.602 E/Xposed  ( 8078):      at bin.xposed.Unblock163MusicClient.Main$1$5.beforeHookedMethod(Unknown Source)
11-06 23:14:35.602 E/Xposed  ( 8078):      at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:314)
11-06 23:14:35.602 E/Xposed  ( 8078):      at com.netease.cloudmusic.ui.a.a.b(<Xposed>)
11-06 23:14:35.602 E/Xposed  ( 8078):      at com.netease.cloudmusic.fragment.p$2.onItemClick(ProGuard:231)
11-06 23:14:35.602 E/Xposed  ( 8078):      at android.widget.AdapterView.performItemClick(AdapterView.java:310)
11-06 23:14:35.602 E/Xposed  ( 8078):      at android.widget.AbsListView.performItemClick(AbsListView.java:1147)
11-06 23:14:35.602 E/Xposed  ( 8078):      at android.widget.AbsListView$PerformClick.run(AbsListView.java:3068)
11-06 23:14:35.602 E/Xposed  ( 8078):      at android.widget.AbsListView$3.run(AbsListView.java:3905)
11-06 23:14:35.602 E/Xposed  ( 8078):      at android.os.Handler.handleCallback(Handler.java:739)
11-06 23:14:35.602 E/Xposed  ( 8078):      at android.os.Handler.dispatchMessage(Handler.java:95)
11-06 23:14:35.602 E/Xposed  ( 8078):      at android.os.Looper.loop(Looper.java:148)
11-06 23:14:35.602 E/Xposed  ( 8078):      at android.app.ActivityThread.main(ActivityThread.java:5481)
11-06 23:14:35.602 E/Xposed  ( 8078):      at java.lang.reflect.Method.invoke(Native Method)
11-06 23:14:35.602 E/Xposed  ( 8078):      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
11-06 23:14:35.602 E/Xposed  ( 8078):      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)

```

**Comment by aviraxp** [comment]
11-07 01:03:49.648 E/Xposed  ( 8078): java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference
11-07 01:03:49.648 E/Xposed  ( 8078): 	at org.json.JSONTokener.nextCleanInternal(JSONTokener.java:116)
11-07 01:03:49.648 E/Xposed  ( 8078): 	at org.json.JSONTokener.nextValue(JSONTokener.java:94)
11-07 01:03:49.648 E/Xposed  ( 8078): 	at org.json.JSONObject.<init>(JSONObject.java:156)
11-07 01:03:49.648 E/Xposed  ( 8078): 	at org.json.JSONObject.<init>(JSONObject.java:173)
11-07 01:03:49.648 E/Xposed  ( 8078): 	at bin.xposed.Unblock163MusicClient.b.c(Unknown Source)
11-07 01:03:49.648 E/Xposed  ( 8078): 	at bin.xposed.Unblock163MusicClient.Main$1$1.afterHookedMethod(Unknown Source)
11-07 01:03:49.648 E/Xposed  ( 8078): 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:348)
11-07 01:03:49.648 E/Xposed  ( 8078): 	at com.netease.cloudmusic.i.b.a(<Xposed>)
11-07 01:03:49.648 E/Xposed  ( 8078): 	at com.netease.cloudmusic.c.a.b.a(ProGuard:7834)
11-07 01:03:49.648 E/Xposed  ( 8078): 	at java.lang.reflect.Method.invoke(Native Method)
11-07 01:03:49.648 E/Xposed  ( 8078): 	at com.netease.cloudmusic.utils.b.invoke(ProGuard:51)
11-07 01:03:49.648 E/Xposed  ( 8078): 	at java.lang.reflect.Proxy.invoke(Proxy.java:393)
11-07 01:03:49.648 E/Xposed  ( 8078): 	at $Proxy0.a(Unknown Source)
11-07 01:03:49.648 E/Xposed  ( 8078): 	at com.netease.cloudmusic.fragment.bt.h(ProGuard:1076)
11-07 01:03:49.648 E/Xposed  ( 8078): 	at com.netease.cloudmusic.fragment.bt.D(ProGuard:98)
11-07 01:03:49.648 E/Xposed  ( 8078): 	at com.netease.cloudmusic.fragment.bt$10.a(ProGuard:636)
11-07 01:03:49.648 E/Xposed  ( 8078): 	at com.netease.cloudmusic.ui.PagerListView$b.a(ProGuard:624)
11-07 01:03:49.648 E/Xposed  ( 8078): 	at com.netease.cloudmusic.ui.PagerListView$b.b(ProGuard:592)
11-07 01:03:49.648 E/Xposed  ( 8078): 	at com.netease.cloudmusic.d.r.doInBackground(ProGuard:160)
11-07 01:03:49.648 E/Xposed  ( 8078): 	at android.os.AsyncTask$2.call(AsyncTask.java:295)
11-07 01:03:49.648 E/Xposed  ( 8078): 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
11-07 01:03:49.648 E/Xposed  ( 8078): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
11-07 01:03:49.648 E/Xposed  ( 8078): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
11-07 01:03:49.648 E/Xposed  ( 8078): 	at java.lang.Thread.run(Thread.java:818)

**Comment by bin456789** [comment]
我这里不能重现这些问题呀
你是怎么操作的？
这些错误是经常出现还是只出现一两次？

**Comment by aviraxp** [comment]
我的锅，我知道问题在哪了。

但是歌曲名还是灰的…………

**Comment by bin456789** [comment]
这版灰色才是正常的

**Comment by aviraxp** [comment]
重现了NoSuchField

**Comment by bin456789** [comment]
咋重现的？

**Comment by aviraxp** [comment]
刚又来了个IllegalArgumentException，不过我无法确切捕捉到是什么时候产生的。我会进一步跟进的。

**Comment by zimoua** [comment]
求apk

**Comment by neoFelhz** [comment]
@zimoua There are not newest apk here.Just clone the code and import it to the Audroid Studio to build it yourself.

**Comment by zimoua** [comment]
嗯嗯

**Comment by bin456789** [comment]
目测三个问题都已解决，做个标记

第一个问题
点击动态里的评论会触发，IllegalArgumentException也是同一个问题
区别在于，如果歌曲播放界面里显示过音质选择框则触发IllegalArgumentException，否则触发NoSuchFieldError

解决办法是在这里加了判断，应该不会报错了
https://github.com/bin456789/Unblock163MusicClient-Xposed/blob/0.0.14/app/src/main/java/bin/xposed/Unblock163MusicClient/Main.java#L185

第二个问题
貌似因为这里new JSONObject(null)
https://github.com/bin456789/Unblock163MusicClient-Xposed/blob/0.0.14/app/src/main/java/bin/xposed/Unblock163MusicClient/Handler.java#L104

解决办法是在这里加了判断，应该不会报错了
https://github.com/bin456789/Unblock163MusicClient-Xposed/blob/0.0.14/app/src/main/java/bin/xposed/Unblock163MusicClient/Main.java#L65
