### ISSUE TITLE
最新版本无效

### ISSUE THREAD

**Issue by zcong1993** [bin456789/Unblock163MusicClient-Xposed#33]
是否支持最新版本

**Comment by bin456789** [comment]
最新版不是3.7.4？我这边可用
如果歌曲变灰的话，点击也是可以播放的

**Comment by zcong1993** [comment]
@bin456789 下载不了歌曲，重装了还是不行，好像，我下了个3.7.3，一切正常

**Comment by aviraxp** [comment]
你用的是哪个版本？

**Comment by zcong1993** [comment]
@aviraxp 3.7.4不能下载歌曲，好像也播放不了

**Comment by aviraxp** [comment]
我说你的音量增强器

**Comment by zcong1993** [comment]
0.0.12

**Comment by aviraxp** [comment]
拿现在这个源码，重新编译

**Comment by zcong1993** [comment]
感谢，我得学学怎么编译apk了。。。jser压力山大

**Comment by bin456789** [comment]
0.0.13有点问题，所以发布apk后又删除了
不过貌似也不影响使用，我等下再重新发布下apk

**Comment by zcong1993** [comment]
@bin456789 非常感谢。辛苦了
