### ISSUE TITLE
下架的歌曲查看时显示为灰色状态

### ISSUE THREAD

**Issue by zjns** [bin456789/Unblock163MusicClient-Xposed#35]
下架的歌曲查看时显示为灰色状态，能不能完善下，像原来一样显示为黑色，虽然不影响下载和播放。。。

**Comment by wst4288** [comment]
能用就可以了吧。下个版本再更新。

**Comment by bin456789** [comment]
这是 feature，不会修复
但为了世界的和平
我还是把显示黑色的上传了上来
链接：http://pan.baidu.com/s/1qYpk7bI 密码：yp9k

**Comment by zjns** [comment]
不仅还是显示为灰色，而且不能播放下载了。。。。

**Comment by bin456789** [comment]
@zjns 你指的是百度云上那个？这不科学

**Comment by zjns** [comment]
@bin456789 再装了一次又好了，应该是我这边之前操作有问题，模块没问题。让你受惊了。。。
