### ISSUE TITLE
编译时发生错误

### ISSUE THREAD

**Issue by OuSatoru** [bin456789/Unblock163MusicClient-Xposed#39]
Error:(15, 0) Could not get unknown property 'STORE_FILE' for SigningConfig_Decorated{name=release, storeFile=null, storePassword=null, keyAlias=null, keyPassword=null, storeType=null, v1SigningEnabled=true, v2SigningEnabled=true} of type com.android.build.gradle.internal.dsl.SigningConfig.
<a href="openFile:E:\Work\AndroidProj\Unblock163MusicClient-Xposed-master\app\build.gradle">Open File</a>
请教一下

**Comment by aviraxp** [comment]
把build.gradle里作者自己的编译信息删掉

**Comment by OuSatoru** [comment]
我把release{ }里都删掉了，好像变成了debug模式，不过已经能装上手机了，谢谢

**Comment by zay448345045** [comment]
不是有编译好的release直接下吗
