### ISSUE TITLE
请问这个KEY_ALIAS等四个属性是什么意思

### ISSUE THREAD

**Issue by bornbeauty** [bin456789/Unblock163MusicClient-Xposed#4]
我如何添加这些属性呢

**Comment by bin456789** [comment]
release 模式下要用自己的 key 签名，这几个就是 key 相关的东西
你可以在 gradle.properties 添加这些东西
KEY_ALIAS=xxx
KEY_PASSWORD=yyy
STORE_FILE=path/to/zzz.jks
STORE_PASSWORD=aaa




如果直接用 debug 模式生成，删除 signingConfig 相关的内容，应该就没问题了

**Comment by bornbeauty** [comment]
好的~ 多谢

2016-04-13 

zhongjinbao1994 



发件人：王煎饼 <notifications@github.com>
发送时间：2016-04-13 16:56
主题：Re: [bin456789/Unblock163MusicClient-Xposed] 请问这个KEY_ALIAS等四个属性是什么意思 (#4)
收件人："bin456789/Unblock163MusicClient-Xposed"<Unblock163MusicClient-Xposed@noreply.github.com>
抄送："jimbo"<zhongjinbao1994@gmail.com>

release 模式下要用自己的 key 签名，这几个就是 key 相关的东西
你可以在 gradle.properties 添加这些东西
KEY_ALIAS=xxx
KEY_PASSWORD=yyy
STORE_FILE=path/to/zzz.jks
STORE_PASSWORD=aaa
如果直接用 debug 模式生成，删除 signingConfig 相关的内容，应该就没问题了
