### ISSUE TITLE
api 又能用了吗？

### ISSUE THREAD

**Issue by happlebao** [bin456789/Unblock163MusicClient-Xposed#40]
api 又能用了吗？

**Comment by bin456789** [comment]
呃，不知道你说哪个api
最早用的 v3/song/detail 这个倒是失效过，我也几天前才发现又好了

不过api倒不是问题，而是很多下架歌曲都404了
这部分歌曲就只能从虾米或者qq音乐上面得到了

**Comment by happlebao** [comment]
谢谢
