### ISSUE TITLE
建议添加付费电台下载功能

### ISSUE THREAD

**Issue by cxlg44** [bin456789/Unblock163MusicClient-Xposed#45]
rt

**Comment by bin456789** [comment]
什么？有付费电台？

**Comment by cxlg44** [comment]
新版本才出来的，分享网易云音乐精品电台《人民的名义》: http://music.163.com/radio?id=349497076&userid=295542016 (来自@网易云音乐)

虽然旧的版本可以绕过下载，但是挺费事的！

**Comment by bin456789** [comment]
实测可行，等网易云更新后添加。。
不过可能需要修改配置文件才能打开这个功能。。
因为这个不是歌曲。。而且网易在推这个电台。。

**Comment by bin456789** [comment]
往日可用 detail api 获取电台的音频网址
但从昨晚开始就不行了
如要能找到其他可用的 api 再添加
