### ISSUE TITLE
某些歌曲无法聆听

### ISSUE THREAD

**Issue by leewp14** [bin456789/Unblock163MusicClient-Xposed#48]
某些歌曲(就一些罢了） 如 the faith, steins gate soundtrack （一般只要一首不能听 那一首歌的歌手的每一首都会遇到同样问题）不能聆听 诺点击聆听 播放器就卡了（就网易app的播放器罢了 网易app还能正常操作）但关掉网易开过就OK了可以正常播放其他歌曲
然后即使无法聆听 这类歌曲还是可以下载的 但是点击下载过后得等很久很久才开始下载（大概15分钟）奇怪就是下载速度竟然正常
我看待会儿我log cat看看 
xposed log 那里没有任何问题啦

**Comment by bin456789** [comment]
http://music.163.com/#/m/song?id=26584165
这首？

**Comment by EricDole** [comment]
现在0.0.017那个版本都听不了付费歌曲。

**Comment by leewp14** [comment]
@bin456789 抱歉我这几天考试 考完试我再试试logcat
对那也是其中 不过那个最后一次尝试已经是前几个星期了 最近我confirm不能的就是尚雯婕的最终信仰orTheFaith还有她的一些歌曲 但是如上面所写 点击下载了等约15分钟还是可以下载

@EricDole 没问题啊 我才下载taylor的歌罢了昨天 而且我还是在海外（没有开启海外模式）

**Comment by leewp14** [comment]
Edit : 问题消失了 谢谢

**Comment by EricDole** [comment]
抱歉，只是安装0.0.017版本的apk的后，听宇多田光的歌都会跳出获取链接失败这提示。
