### ISSUE TITLE
更新后插件仍无效

### ISSUE THREAD

**Issue by dysmux** [bin456789/Unblock163MusicClient-Xposed#53]
十分抱歉!再次发issues.
更新了0.0.18后测试并不能聆听付费音乐
我所使用的网易云是4.1.0版本的(最新版)
希望作者能亲查修复一下 非常感谢!

**Comment by bin456789** [comment]
呃，具体是哪首？最好附上id

**Comment by dysmux** [comment]
比如http://music.163.com/#/song?id=25648017

**Comment by bin456789** [comment]
我这边没问题
你试下删除插件，打开xposed管理器后，再安装一次
我猜测你更新插件的时候，xposed管理器的后台被关闭了
这种情况下，更新可能不生效，我试过几次

**Comment by dysmux** [comment]
刚刚尝试了一下您的方法 发现好使了
但当我随便地点了一首下线音乐 提示资源不存在 然后我又点了一首付费歌曲 又失效了。

**Comment by dysmux** [comment]
刚刚尝试了一下您的方法 发现好使了
但当我随便地点了一首下线音乐 提示资源不存在 然后我又点了一首付费歌曲 又失效了。

**Comment by bin456789** [comment]
呃，歌曲id是？
或者你试下切换wifi/数据

**Comment by dysmux** [comment]
在2分钟前 我又重启手机 
我随便点了一首高音质需要付费的音乐 我的设置里是选择自动播放高音质 但那歌自动切换了128音质 我又在歌曲音质栏里进行操作：先点了自动切换 又点了一下360音质 成功切换。
再点一下下线歌曲和付费歌曲 测试成功
但有一些歌仍是自动切换了128音质
如http://music.163.com/#/song?id=479219347

**Comment by dysmux** [comment]
其实我觉得也可能是网络问题
因为我这里网络出了一点问题😓

**Comment by dysmux** [comment]
刚才我又重启了一下网易云随便点了一首付费歌曲 发现失效…
http://music.163.com/#/song?id=19292800
😰

**Comment by bin456789** [comment]
这个我实在无法解释了。。
你可以打开xposed日志或者装一个matlog看看有没有错误之类的

**Comment by dysmux** [comment]
好的我会尝试的😰

**Comment by aviraxp** [comment]
这么说吧。。。我这里，偶尔扔timeout。

**Comment by dysmux** [comment]
刚刚打开xposed日志看了一下
我发现有几处unknown什么的…
请允许我的无知 我并没有发现关于error之类的字符

**Comment by bin456789** [comment]
@dysmux  应该搜索exception。。不过没有记录有问题的链接。。我的锅。。
@aviraxp 试了下下架音乐，的确有超时
![111](https://cloud.githubusercontent.com/assets/7548515/26498080/5aeaea26-4260-11e7-8054-5443efd6483d.jpg)

我也很绝望啊，看来也要对网易的域名设置超时时间

**Comment by dysmux** [comment]
那…能否修复?😓😓

**Comment by bin456789** [comment]
@dysmux 不清楚，因为不知道是不是同一个问题

**Comment by dysmux** [comment]
😓那非常感谢帮助…虽然我的问题没有得到解决 但是您很热心 我期待下一次的更新😘

**Comment by caliban511** [comment]
新版确实没有效果，期待下次更新。
