### ISSUE TITLE
反馈“服务器发生错误”

### ISSUE THREAD

**Issue by yoyodadada** [bin456789/Unblock163MusicClient-Xposed#60]
手机型号：华为 荣耀7（PLK-AL10）
系统版本：EMUI3.1（Android版本5.0.2）
ROM版本：PLK-AL10C00B188 Advanced by HRT-KillProcess
其它：已解BL锁，已root，已装busybox，已核心破解三项，已装Xopsed框架（v87，管理器v3.0.1 by dvdandroid 29/04/17）
网易云音乐版本：TCL手机专享版，版本显示9.0.0
音量增强器插件版本：0.0.15
情况说明：以前使用均正常，可以正常试听及下载黑色字体及灰色字体音乐，在酷安上发现网友反应插件失效，亲自测试了一下，目前能够试听及下载黑色常规字体音乐，灰色字体音乐只能试听，无法下载，点击下载提示“服务器发生错误”。

**Comment by bin456789** [comment]
反馈非常详细，很好
0.0.20应该可以了

**Comment by yoyodadada** [comment]
可以在线试听了，下载也能走进度条，但是到最后却提示下载失败，是我的网易云音乐版本问题么？测试专辑Katty Perry《Witness》

**Comment by yoyodadada** [comment]
我换了4.1.0-play-LolliKit修改版，配上0.0.20插件，下载歌曲就没问题，同样的专辑，可能是云音乐版本问题吧，旧版本用着其实挺好的。。。

**Comment by bin456789** [comment]
@yoyodadada 
tcl 版本之前说过，这个不会修复
因为特殊处理会对官方版的加载速度有影响
另外其他品牌的定制版也可能有问题，怕开了个坏头
建议用官方版，越新越好。。

**Comment by yoyodadada** [comment]
好的，谢谢大神，关闭这个Issue吧
