### ISSUE TITLE
很遗憾 0.0.20插件并没有起作用。

### ISSUE THREAD

**Issue by dysmux** [bin456789/Unblock163MusicClient-Xposed#63]
网易云测试版本：4.1.0
插件版本：0.0.20
点击泰勒的you belong me 无法播放 提示需要付费。

**Comment by dysmux** [comment]
且xposed日志为空。

**Comment by a545774001** [comment]
我这里没问题
试试重新激活并重启？

**Comment by winhiko** [comment]
更新后无法启用插件？

**Comment by dysmux** [comment]
我是卸载了旧版本的插件重新安装了最新插件
网易云是在官网上下载的 检查更新也没有提示需要更新
我很奇怪。 为什么最近我这里最近插件都无法使用
难道是网络问题？ 如果愿意的话 详情加q…1157079166

**Comment by dysmux** [comment]
并不是插件未生效 而是播放了这首付费歌后缓冲了一会 然后再提示需要付费

**Comment by pzy1998** [comment]
表示可以用，你可以把xposed里的勾取消，再重新勾上，重启就行了。

**Comment by pzy1998** [comment]
重启手机
