### ISSUE TITLE
Play 4.1.1版本搭配0.021无法使用，提示「播放列表所有歌曲都无法播放，已暂停」、「因合作方要求，该资源暂时无法使用」

### ISSUE THREAD

**Issue by Kara-ism** [bin456789/Unblock163MusicClient-Xposed#67]
大神，我手机和电脑上的模拟器都装上了Play 4.1.1版本和0.021的音量适配

但是手机上没法播放，一直提示「播放列表所有歌曲都无法播放，已暂停」、「因合作方要求，该资源暂时无法使用」

但是模拟器上能正常使用…

模拟器上和手机上登录的号是一样的，不知道能否请大神看下怎麽修复麽? 真的很谢谢 :smiley: 

模拟器的资讯
--
OS版本号：BlueStacks 4.4.2
Xposed app_process版本号：58
XposedBridge.jar版本号：54

手机的资讯
--
OS版本号：LG G Pro 2 5.0.1
Xposed 版本号：87

Log文件 [xposed_error_20170627_111427.txt](https://github.com/bin456789/Unblock163MusicClient-Xposed/files/1104118/xposed_error_20170627_111427.txt)

![screenshot 2017 6 27 11-33-45](https://user-images.githubusercontent.com/9511279/27569947-123b768e-5b2d-11e7-93f6-9ce68e1bfd4c.png)

![screenshot_2017-06-27-11-29-47](https://user-images.githubusercontent.com/9511279/27569946-1236fb40-5b2d-11e7-9d1f-ba4aa40be650.png)

**Comment by bin456789** [comment]
你的log非常有用
删除 /data/data/com.netease.cloudmusic/shared_perfs/multidex.version.xml 试试看

**Comment by Kara-ism** [comment]
@bin456789 太神奇了 大神 :open_mouth: 

删除那个文件就能用了，太感谢了！
谢谢大神！！ :laughing:

**Comment by bin456789** [comment]
你的手机是从4.4升级到5.0，而且升级后没有重装过网易云？

**Comment by Kara-ism** [comment]
@bin456789 这也能知道阿 :rofl: 
对 从4.4升级到5.0，用钛备份直接还原的

**Comment by bin456789** [comment]
4.4及以下会生成 /data/data/com.netease.cloudmusic/shared_perfs/multidex.version.xml
和 /data/data/com.netease.cloudmusic/code_cache/secondary-dexes/ 这个文件夹
如果有 multidex.version.xml 而且 dex.number >=2，那就要从secondary-dexes 文件夹读取内容


升级到5.0后，secondary-dexes 文件夹被系统删除了
但 multidex.version.xml 还是原来的，所以插件依然会从那个文件夹读取内容，由于代码没考虑到这种情况，就出问题了


而删除那个文件后，插件就不会读取 secondary-dexes 的内容了，所以正常了

**Comment by Kara-ism** [comment]
了解了，谢谢！ :smile:
