### ISSUE TITLE
网易云音乐 4.2.0.310743(coolapk) 已失效

### ISSUE THREAD

**Issue by AnyoeDove** [bin456789/Unblock163MusicClient-Xposed#79]
酷安当前上架的一个版本 版本号为4.2.0.310743 软件版本号103(官方下载链接显示404)
https://drive.google.com/file/d/0B3WQsb8rrN8lS0VGZHI1NjZ1VUE/view?usp=sharing

官网目前最新版本号为4.2.0.788545 软件版本号102

另外该版本很奇怪的是/META-INF/CLOUDMUSICCHANNEL_coolapk

**Comment by lxl6125** [comment]
别升级就行了，旧版又不是不能用
