### ISSUE TITLE
关于增强器失效问题的解释

### ISSUE THREAD

**Issue by LoneShore** [bin456789/Unblock163MusicClient-Xposed#85]
这不是网易云的锅，而是作者故意设置的，作者在增强器里加入了时间判断机制，在2017-10-01之后增强器将彻底失效。

**Comment by LoneShore** [comment]
酷安网（@孤岸）首发，未经允许禁止转载。

**Comment by Gestepo** [comment]
感谢分享。

**Comment by SnowRain1326** [comment]
哈哈哈我刚好截了某大佬发的修改版发到了酷安
2017年10月1日 下午9:10于 Gestepo <notifications@github.com>写道：感谢分享。

**Comment by Gestepo** [comment]
我一般是来这边看，你给的🤗很舒服。

2017-10-01 21:14 GMT+08:00 SnowRain1326 <notifications@github.com>:

**Comment by SnowRain1326** [comment]
我也更喜欢在这边看
2017年10月1日 21:17于 Gestepo <notifications@github.com>写道：

**Comment by caliban511** [comment]
感谢楼主分享。
也希望大佬早日恢复更新。
