### ISSUE TITLE
修改版本分享，解决模块无法激活/使用问题

### ISSUE THREAD

**Issue by leewp14** [bin456789/Unblock163MusicClient-Xposed#86]
前几天看到有人分享了问题来源 我也不确定那些版本是拆apk来修改还是build from source的。自己尝试了fork然后做了修改 目前内测没有问题 :-)
[https://github.com/leewp14/xposed.leewp14.NEClient/releases](https://github.com/leewp14/xposed.leewp14.NEClient/releases)

能的话请留言模块是否可以正常操作，谢谢！因为我在海外，不能测试全部功能
我的测试环境为OmniROM 4.4.4, xposed 2.7, NetEase Music 4.2.0.771946

**Comment by wl745215924** [comment]
可以用，但是有些歌曲没法下载了，

**Comment by wl745215924** [comment]
好像是网易云加了新的限制，陈奕迅的新专辑没法下载，其他的基本没问题

**Comment by nikzhang2016** [comment]
基本可以正常使用了，非常感谢！
存在的问题是：有些专辑里的版权曲会变成“未知track”，试图播放时提示“资源不存在”，可能是网易云做的新限制，如图。
![未知track](https://i.imgur.com/nq4GKrD.png)
![资源不存在](https://i.imgur.com/tib4FDf.png)

**Comment by CoderGrowing** [comment]
环境：小米6，Android 7.1.1，MIUI 9 - 7.9.14官方俄罗斯版
没有效果。Xposed日志如下：
10-03 15:02:38.077 I/Xposed  (  852): -----------------
10-03 15:02:38.077 I/Xposed  (  852): Starting Xposed version 87 (MIUI edition by SolarWarez based on PurifyOS release / 20170821), compiled for SDK 25
10-03 15:02:38.077 I/Xposed  (  852): Device: MI 6 (Xiaomi), Android version 7.1.1 (SDK 25)
10-03 15:02:38.077 I/Xposed  (  852): ROM: NMF26X
10-03 15:02:38.077 I/Xposed  (  852): Build fingerprint: Xiaomi/sagit/sagit:7.1.1/NMF26X/7.9.14:user/release-keys
10-03 15:02:38.078 I/Xposed  (  852): Platform: arm64-v8a, 64-bit binary, system server: yes
10-03 15:02:38.078 I/Xposed  (  852): SELinux enabled: yes, enforcing: yes
10-03 15:02:39.097 I/Xposed  (  852): -----------------
10-03 15:02:39.097 I/Xposed  (  852): Added Xposed (/system/framework/XposedBridge.jar) to CLASSPATH
10-03 15:02:39.340 I/Xposed  (  852): Detected ART runtime
10-03 15:02:39.345 I/Xposed  (  852): Found Xposed class 'de/robv/android/xposed/XposedBridge', now initializing
10-03 15:02:39.538 I/Xposed  (  852): Loading modules from /data/app/com.blanke.mdwechat-1/base.apk
10-03 15:02:39.549 I/Xposed  (  852):   Loading class com.blanke.mdwechat.WechatHook
10-03 15:02:39.551 I/Xposed  (  852): Loading modules from /data/app/com.jozein.xedge-1/base.apk
10-03 15:02:39.561 I/Xposed  (  852):   Loading class com.jozein.xedge.xposed.HookMain
10-03 15:02:39.576 I/Xposed  (  852): Loading modules from /data/app/com.fkzhang.wechatxposed-2/base.apk
10-03 15:02:39.588 I/Xposed  (  852):   Loading class com.fkzhang.wechatxposed.XposedInit
10-03 15:02:39.591 I/Xposed  (  852): Loading modules from /data/app/com.specher.music163-1/base.apk
10-03 15:02:39.602 I/Xposed  (  852):   Loading class com.specher.music163.Hook
10-03 15:02:39.603 I/Xposed  (  852): Loading modules from /data/app/xposed.leewp14.NEClient-1/base.apk
10-03 15:02:39.611 I/Xposed  (  852):   Loading class xposed.leewp14.NEClient.Main
10-03 15:02:47.763 I/Xposed  (  853): -----------------
10-03 15:02:47.763 I/Xposed  (  853): Starting Xposed version 87 (MIUI edition by SolarWarez based on PurifyOS release / 20170821), compiled for SDK 25
10-03 15:02:47.763 I/Xposed  (  853): Device: MI 6 (Xiaomi), Android version 7.1.1 (SDK 25)
10-03 15:02:47.763 I/Xposed  (  853): ROM: NMF26X
10-03 15:02:47.763 I/Xposed  (  853): Build fingerprint: Xiaomi/sagit/sagit:7.1.1/NMF26X/7.9.14:user/release-keys
10-03 15:02:47.763 I/Xposed  (  853): Platform: arm64-v8a, 32-bit binary, system server: no
10-03 15:02:47.763 I/Xposed  (  853): SELinux enabled: yes, enforcing: yes
10-03 15:02:47.764 I/Xposed  (  853): -----------------
10-03 15:02:47.764 I/Xposed  (  853): Added Xposed (/system/framework/XposedBridge.jar) to CLASSPATH
10-03 15:02:47.970 I/Xposed  (  853): Detected ART runtime
10-03 15:02:47.974 I/Xposed  (  853): Found Xposed class 'de/robv/android/xposed/XposedBridge', now initializing
10-03 15:02:48.118 I/Xposed  (  853): Loading modules from /data/app/com.blanke.mdwechat-1/base.apk
10-03 15:02:48.126 I/Xposed  (  853):   Loading class com.blanke.mdwechat.WechatHook
10-03 15:02:48.129 I/Xposed  (  853): Loading modules from /data/app/com.jozein.xedge-1/base.apk
10-03 15:02:48.136 I/Xposed  (  853):   Loading class com.jozein.xedge.xposed.HookMain
10-03 15:02:48.149 I/Xposed  (  853): Loading modules from /data/app/com.fkzhang.wechatxposed-2/base.apk
10-03 15:02:48.157 I/Xposed  (  853):   Loading class com.fkzhang.wechatxposed.XposedInit
10-03 15:02:48.158 I/Xposed  (  853): Loading modules from /data/app/com.specher.music163-1/base.apk
10-03 15:02:48.164 I/Xposed  (  853):   Loading class com.specher.music163.Hook
10-03 15:02:48.164 I/Xposed  (  853): Loading modules from /data/app/xposed.leewp14.NEClient-1/base.apk
10-03 15:02:48.170 I/Xposed  (  853):   Loading class xposed.leewp14.NEClient.Main
10-03 15:02:51.574 E/Xposed  ( 1818): Zygote service is not accessible from PID 1818, UID 1000
10-03 15:02:51.577 E/Xposed  ( 1818): Zygote service is not accessible from PID 1818, UID 1000
10-03 15:03:00.792 I/Xposed  ( 4358): music163plus:Loaded music163.
10-03 15:03:02.263 E/Xposed  ( 4358): java.lang.RuntimeException: init failed
10-03 15:03:02.263 E/Xposed  ( 4358): at xposed.leewp14.NEClient.a.a(Unknown Source)
10-03 15:03:02.263 E/Xposed  ( 4358): at xposed.leewp14.NEClient.Main$1.afterHookedMethod(Unknown Source)
10-03 15:03:02.263 E/Xposed  ( 4358): at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:350)
10-03 15:03:02.263 E/Xposed  ( 4358): at android.app.Application.attach(Unknown Source)
10-03 15:03:02.263 E/Xposed  ( 4358): at android.app.Instrumentation.newApplication(Instrumentation.java:1009)
10-03 15:03:02.263 E/Xposed  ( 4358): at android.app.Instrumentation.newApplication(Instrumentation.java:993)
10-03 15:03:02.263 E/Xposed  ( 4358): at android.app.LoadedApk.makeApplication(LoadedApk.java:800)
10-03 15:03:02.263 E/Xposed  ( 4358): at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5471)
10-03 15:03:02.263 E/Xposed  ( 4358): at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
10-03 15:03:02.263 E/Xposed  ( 4358): at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:336)
10-03 15:03:02.263 E/Xposed  ( 4358): at android.app.ActivityThread.handleBindApplication(Unknown Source)
10-03 15:03:02.263 E/Xposed  ( 4358): at android.app.ActivityThread.-wrap2(ActivityThread.java)
10-03 15:03:02.263 E/Xposed  ( 4358): at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1590)
10-03 15:03:02.263 E/Xposed  ( 4358): at android.os.Handler.dispatchMessage(Handler.java:102)
10-03 15:03:02.263 E/Xposed  ( 4358): at android.os.Looper.loop(Looper.java:163)
10-03 15:03:02.263 E/Xposed  ( 4358): at android.app.ActivityThread.main(ActivityThread.java:6276)
10-03 15:03:02.263 E/Xposed  ( 4358): at java.lang.reflect.Method.invoke(Native Method)
10-03 15:03:02.263 E/Xposed  ( 4358): at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:898)
10-03 15:03:02.263 E/Xposed  ( 4358): at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:788)
10-03 15:03:02.263 E/Xposed  ( 4358): at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:104)
10-03 15:03:02.845 I/Xposed  ( 4358): music163plus:已删除:/storage/emulated/0/netease/cloudmusic/Ad/Image
10-03 15:03:02.846 I/Xposed  ( 4358): music163plus:已删除:/storage/emulated/0/netease/cloudmusic/Ad/Video
10-03 15:03:05.020 I/Xposed  ( 4675): music163plus:Loaded music163.
10-03 15:03:10.566 E/Xposed  ( 4675): java.lang.RuntimeException: init failed
10-03 15:03:10.566 E/Xposed  ( 4675): at xposed.leewp14.NEClient.a.a(Unknown Source)
10-03 15:03:10.566 E/Xposed  ( 4675): at xposed.leewp14.NEClient.Main$1.afterHookedMethod(Unknown Source)
10-03 15:03:10.566 E/Xposed  ( 4675): at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:350)
10-03 15:03:10.566 E/Xposed  ( 4675): at android.app.Application.attach(Unknown Source)
10-03 15:03:10.566 E/Xposed  ( 4675): at android.app.Instrumentation.newApplication(Instrumentation.java:1009)
10-03 15:03:10.566 E/Xposed  ( 4675): at android.app.Instrumentation.newApplication(Instrumentation.java:993)
10-03 15:03:10.566 E/Xposed  ( 4675): at android.app.LoadedApk.makeApplication(LoadedApk.java:800)
10-03 15:03:10.566 E/Xposed  ( 4675): at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5471)
10-03 15:03:10.566 E/Xposed  ( 4675): at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
10-03 15:03:10.566 E/Xposed  ( 4675): at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:336)
10-03 15:03:10.566 E/Xposed  ( 4675): at android.app.ActivityThread.handleBindApplication(Unknown Source)
10-03 15:03:10.566 E/Xposed  ( 4675): at android.app.ActivityThread.-wrap2(ActivityThread.java)
10-03 15:03:10.566 E/Xposed  ( 4675): at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1590)
10-03 15:03:10.566 E/Xposed  ( 4675): at android.os.Handler.dispatchMessage(Handler.java:102)
10-03 15:03:10.566 E/Xposed  ( 4675): at android.os.Looper.loop(Looper.java:163)
10-03 15:03:10.566 E/Xposed  ( 4675): at android.app.ActivityThread.main(ActivityThread.java:6276)
10-03 15:03:10.566 E/Xposed  ( 4675): at java.lang.reflect.Method.invoke(Native Method)
10-03 15:03:10.566 E/Xposed  ( 4675): at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:898)
10-03 15:03:10.566 E/Xposed  ( 4675): at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:788)
10-03 15:03:10.566 E/Xposed  ( 4675): at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:104)
10-03 15:03:39.061 E/XposedInstaller( 5858): AdvancedInstallerFragment -> No route to host
10-03 15:03:45.058 E/XposedInstaller( 5858): AdvancedInstallerFragment -> No route to host
10-03 15:03:47.772 I/XposedInstaller( 5858): RepoLoader -> Downloaded http://dl.xposed.info/repo/partial/12876.xml.gz with status 0 (error: null), size 66 bytes
10-03 15:03:47.776 I/XposedInstaller( 5858): RepoLoader -> Updated repository http://dl.xposed.info/repo/full.xml.gz to version 12876 (0 new / 0 removed modules)

**Comment by EricDole** [comment]
安装模块后重启手机多次，还是不能破解那些没版权的歌曲

**Comment by leewp14** [comment]
资源不存在的问题并不是新限制/bug。的确是资源不存在。
未知track也不是新限制/bug。的确是未知track。
@CoderGrowing 尝试set SELINUX to permissive

case 1 : 资源不存在
查看评论数量-没有评论。[BTS - DNA](http://music.163.com/#/song?id=506094567)

case 2 : 未知track
查看评论。[C'mon in~](http://music.163.com/#/album?id=36304576)
![image](https://user-images.githubusercontent.com/17796518/31114654-b3d911ce-a851-11e7-9a4a-c833b66b8022.png)

**Comment by leewp14** [comment]
诺想尝试资源是否存在，可使用这个[网站](https://m1.jixun.moe/) :smiley:

**Comment by leewp14** [comment]
@EricDole 请问是哪些没有版权的歌曲？

**Comment by caliban511** [comment]
感谢楼主分享。。。。

**Comment by EricDole** [comment]
![s71003-194932](https://user-images.githubusercontent.com/28810223/31123837-4b5f2ed0-a874-11e7-9515-461b02bfa6ae.jpg)
![s71003-194956](https://user-images.githubusercontent.com/28810223/31123845-526a29b4-a874-11e7-9f2c-e8f70a792441.jpg)
一直出现这种情况，重启模块后，陈奕迅等无版权的还是听不了

**Comment by leewp14** [comment]
@EricDole 试试看2017.10-1版本 我刚刚release的

**Comment by EricDole** [comment]
@leewp14 装了新模块还是一样没运行。。其他模块都能运行。：-（

**Comment by leewp14** [comment]
@EricDole 我这里4.2.0.771946，安卓4.4，没问题哦 :/

**Comment by nikzhang2016** [comment]
@leewp14 谢谢解惑！

**Comment by leewp14** [comment]
@nikzhang2016 不客气 :smile: 
能否帮我查看一首歌 DREAMCATCHER 的 Before & After (Intro)？这首好像是存在 但模块好像无法获取资源

**Comment by nikzhang2016** [comment]
@leewp14 我的没有任何问题，在电脑上也可以直接播放，说明这首没有被版权。
[Imgur](https://i.imgur.com/2RLHntU.png)
[Imgur](https://i.imgur.com/fztCbPP.png)

**Comment by leewp14** [comment]
@nikzhang2016 噢噢 看来应该是我的地区的关系。我一直得到error资源不存在。但也奇怪有模块也获取不到。

**Comment by wl745215924** [comment]
witness这首歌没有版权，不能听

**Comment by leewp14** [comment]
@wl745215924 https://m1.jixun.moe/ 那里也找不到资源。请问您的地区是？

**Comment by leewp14** [comment]
关于这个歌那个歌不能听 我是不会解决的 因为我没有完全了解云音乐的api是怎样的 我也不会怎样写xposed模块的 我只会java罢了:rofl:  除非有谁知道问题根源的 知道怎样解决 可以submit pull request
这个模块只是供大家暂时使用罢了 等bin456789更新了 我就不会再更新我的版本的了（其实应该不会更新了吧）

**Comment by leewp14** [comment]
bin456789以更新, close issue
