### ISSUE TITLE
有的歌无法下载，提示仅限会员。。。。。

### ISSUE THREAD

**Issue by caliban511** [bin456789/Unblock163MusicClient-Xposed#91]
如题。
例子如下：
陈奕迅的单曲《爱情转移(国) (电影《爱情呼叫转移》主题曲)》: http://music.163.com/song/65099/?userid=68782521

**Comment by kmahyyg** [comment]
我觉得这个模块是用来帮助用户收听下架歌曲，不应该被用于盗版。
请购买会员。

虽然我也用这个模块，不过我购买了年费会员。
![Capture2.PNG](https://i.loli.net/2017/10/17/59e5f2d145607.png)
